config/routes.rb
Rails.application.routes.draw do
  resources :services
  resources :identifies
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  root 'users#new'
  resources :users
  resources :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/saml/auth' => 'saml_idp#new'
  # get '/saml/metadata' => 'saml_idp#show'
  # post '/saml/auth' => 'saml_idp#create'
  # match '/saml/logout' => 'saml_idp#logout', via: [:get, :post, :delete]
  get '/saml/create_saml_request' => 'saml_idp#create_saml_request'
  get '/saml/auth' => 'saml_idp#new'
  get '/saml/metadata' => 'saml_idp#show'
  post '/saml/auth' => 'saml_idp#create'
  match '/saml/logout' => 'saml_idp#logout', via: [:get, :post, :delete]
  post '/saml/call_sp' => 'saml_idp#call_sp'
end

app/controllers/identifies_controller.rb
class IdentifiesController < ApplicationController
  def new
    session['SAMLRequest'] = params['SAMLRequest']
    @saml = SamlTool::Decoder.decode(params['SAMLRequest'])
    @data = SamlRequestReader.new(@saml)
  end
  
  #TODO Need to add handling of RelayState
  def create
    request_data = SamlTool::Decoder.decode(session['SAMLRequest'])
    @saml_request = SamlRequestReader.new(request_data)
    @target = @saml_request.assertion_consumer_service_url
    Rails.logger.warn "Target is #{Rails.logger.info}"
    saml = SamlTool::ErbBuilder.build(
      template: saml_response_template,
      settings: response_settings
    )
    unsigned_assertion = Xmldsig::SignedDocument.new(saml)
    signed_assertion = unsigned_assertion.sign(open_ssl_rsa_key)

    response_saml = SamlTool::ResponseReader.new(signed_assertion)
    Rails.logger.info "Response valid? #{response_saml.valid?}"
    
    @saml_response = SamlTool::Encoder.encode(signed_assertion)
  end
  
  private
  def saml_response_template
    File.read File.expand_path('identifies/response.saml.erb', view_paths.first)
  end
  
  def response_settings
    @response_settings ||= SamlTool::Settings.new(
      issuer: root_url,
      name_id: params['email'],
      not_on_or_after: 10.minutes.from_now.utc.iso8601,
      request: @saml_request,
      certificate: certificate,
      rsa_key: rsa_key,
      attributes: {
        email: params['email']
      }
    )
  end

  def certificate
    @certificate ||= SamlTool::Certificate.new(x509_certificate)
  end

  def rsa_key
    @rsa_key ||= SamlTool::RsaKey.new(open_ssl_rsa_key)
  end


  def x509_certificate
    @x509_certificate ||= OpenSSL::PKCS12.new(
      contents_of('example_files/usercert.p12'),
      'hello'
    ).certificate
  end

  def open_ssl_rsa_key
    @open_ssl_rsa_key ||= OpenSSL::PKey::RSA.new(
      contents_of('example_files/userkey.pem'),
      'hello'
    )
  end

  def contents_of(file_path)
    File.read File.expand_path(file_path, Rails.root)
  end

end

app/views/identifies/create.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body onload="document.forms[0].submit();" style="visibility:hidden;">
    <%= form_tag(@target, method: :put) do %>
      <%= hidden_field_tag("SAMLResponse", @saml_response) %>
      <%= hidden_field_tag("RelayState", params[:RelayState]) %>
      <%= submit_tag "Submit" %>
    <% end %>
  </body>
</html>
<%#
# inspired by
# https://github.com/sportngin/saml_idp/blob/eacdf44561eb98113930cd9f39bbfe09c32d4174/app/views/saml_idp/idp/saml_post.html.erb
%>

app/views/identifies/new.html.erb
<h1>Identity Provider</h1>
<p>A request has been received from a Service Provider</p>

<h2>Please identify yourself</h2>

<%= form_tag(identifies_path) do %>

<dl>
  <dt><%= label_tag :email %></dt>
    <dd><%= text_field_tag :email %></dd>
  <dt><%= label_tag :password %></dt>
    <dd><%= password_field_tag :password %></dd>
</dl>

  <%= submit_tag 'Log in' %>
<% end %>

<h2>Received request</h2>
<%= content_tag('pre', prettify(@saml)) %>

<h2>Data</h2>
<dl>
<% @data.to_hash.each do |key, value|  %>
  <dt><%= key %></dt>
  <dd><%= value %></dd>
<% end %>
</dl>

app/views/identifies/response.saml.erb
<samlp:Response xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="GOSAMLR12901174571794" Version="2.0" IssueInstant="<%= settings.issue_instance %>" Destination="{recipient}">
  <samlp:Status>
    <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></samlp:Status>
  <saml:Assertion xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" Version="2.0" ID="<%= settings.uuid %>" IssueInstant="<%= settings.issue_instance %>">
    <saml:Issuer><%= settings.issuer %></saml:Issuer>
    <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
     <SignedInfo>
      <CanonicalizationMethod Algorithm=
       "http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
      <SignatureMethod Algorithm=
       "http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
      <Reference URI="#<%= settings.uuid %>">
       <Transforms>
        <Transform Algorithm=
         "http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
       </Transforms>
       <DigestMethod Algorithm=
         "http://www.w3.org/2000/09/xmldsig#sha1"/>
       <DigestValue></DigestValue>
      </Reference>
     </SignedInfo>
     <SignatureValue />
     <KeyInfo>
      <X509Data >
       <X509SubjectName><%= settings.certificate.subject_name %></X509SubjectName>
       <X509IssuerSerial>
         <X509IssuerName><%= settings.certificate.issuer_name %></X509IssuerName>
         <X509SerialNumber><%= settings.certificate.serial_number %></X509SerialNumber>
       </X509IssuerSerial>
       <X509Certificate><%= settings.certificate.x509_certificate %></X509Certificate>
      </X509Data>
      <KeyValue>
       <RSAKeyValue>
       <Modulus><%= settings.rsa_key.modulus %></Modulus>
       <Exponent><%= settings.rsa_key.exponent %></Exponent>
       </RSAKeyValue>
       </KeyValue>
     </KeyInfo>
    </Signature>
    <saml:Subject>
      <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress"><%= settings.name_id %></saml:NameID>
      <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml:SubjectConfirmationData NotOnOrAfter="<%= settings.not_on_or_after %>" Recipient="{recipient}"/></saml:SubjectConfirmation>
    </saml:Subject>
    <saml:Conditions NotBefore="<%= settings.issue_instance %>" NotOnOrAfter="<%= settings.not_on_or_after  %>">
      <saml:AudienceRestriction>
        <saml:Audience>{audience}</saml:Audience>
      </saml:AudienceRestriction>
    </saml:Conditions>
    <saml:AuthnStatement AuthnInstant="<%= settings.request.issue_instant %>" SessionNotOnOrAfter="<%= settings.not_on_or_after %>" SessionIndex="<%= settings.request.id %>">
      <saml:AuthnContext>
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
      </saml:AuthnContext>
    </saml:AuthnStatement>
    <saml:AttributeStatement>
<% settings.attributes.each do |key, value| %>
      <saml:Attribute Name="<%= key %>">
        <saml:AttributeValue xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string"><%= value %></saml:AttributeValue>
      </saml:Attribute>
<% end %>
    </saml:AttributeStatement>
  </saml:Assertion>
</samlp:Response>